app/models.py
from flask_sqlalchemy import SQLAlchemy
from flask_migrate import Migrate
import uuid
from datetime import datetime
from werkzeug.security import generate_password_hash, check_password_hash
from flask_login import UserMixin
from flask_login import LoginManager
from flask_marshmallow import Marshmallow
import secrets

Login_manager = LoginManager()
ma = Marshmallow()
db = SQLAlchemy()

@Login_manager.user_loader
def load_user(user_id):
    return User.query.get(user_id)


class User(db.Model, UserMixin):
    id = db.Column(db.String, primary_key=True)
    first_name = db.Column(db.String(150), nullable=True, default='')
    last_name = db.Column(db.String(150), nullable = True, default = '')
    email = db.Column(db.String(150), nullable = False)
    password = db.Column(db.String, nullable = True, default = '')
    g_auth_verify = db.Column(db.Boolean, default = False)
    token = db.Column(db.String, default = '', unique = True )
    date_created = db.Column(db.DateTime, nullable = False, default = datetime.utcnow)

    def __init__(self, email, first_name='', last_name='', password='', token='', g_auth_verify=False):
        self.id = self.set_id()
        self.first_name = first_name
        self.last_name = last_name
        self.password = self.set_password(password)
        self.email = email
        self.token = self.set_token(24)
        self.g_auth_verify = g_auth_verify

    def set_token(self, length):
        return secrets.token_hex(length)

    def set_id(self):
        return str(uuid.uuid4())
    
    def set_password(self, password):
        self.pw_hash = generate_password_hash(password)
        return self.pw_hash

    def __repr__(self):
        return f'User {self.email} has been added to the database'
    
class Car(db.Model):
    id = db.Column(db.String, primary_key = True)
    car = db.Column(db.String(50))
    name = db.Column(db.String(150), nullable = False)
    model = db.Column(db.String(20))
    year = db.Column(db.String(4))
    color = db.Column(db.String(20))
    gas = db.Column(db.String(15))
    Mpg = db.Column(db.Integer())
    engine = db.Column(db.String(4))
    user_token = db.Column(db.String, db.ForeignKey('user.token'), nullable = False)

    def __init__(self, car, name, model, year, color, gas, Mpg, engine, user_token, id = ''):
        self.id = self.set_id()
        self.car  = car
        self.name = name
        self.model = model
        self.year = year
        self.color = color
        self.gas = gas
        self.Mpg = Mpg
        self.engine = engine
        self.user_token = user_token


    def __repr__(self):
        return f'The following car has been added to the App: {self.name}'

    def set_id(self):
        return (secrets.token_urlsafe())

class CarSchema(ma.Schema):
    class Meta:
        fields = ['id', 'car', 'name','model','year', 'color','gas', 'Mpg', 'engine']

cars_schema = CarSchema()

app/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, SubmitField
from wtforms.validators import DataRequired, Email

class UserLoginForm(FlaskForm):
    email = StringField('Email', validators = [DataRequired(), Email()])
    password = PasswordField('Password', validators = [DataRequired()])
    submit_button = SubmitField()

app/__init__.py
from flask import Flask 
from config import Config 
from .site.routes import site
from .auth.routes import auth
from .api.routes import api

from flask_sqlalchemy import SQLAlchemy 
from flask_migrate import Migrate
from .models import db as root_db, Login_manager, ma 
from flask_cors import CORS
from .helpers import JSONEncoder

app = Flask(__name__)
CORS(app)

app.register_blueprint(site)
app.register_blueprint(auth)
app.register_blueprint(api)

app.json_encoder = JSONEncoder
app.config.from_object(Config)
root_db.init_app(app)
Login_manager.init_app(app)
ma.init_app(app)
migrate = Migrate(app, root_db)

app/api/routes.py
from flask import Blueprint, request, jsonify, render_template
from ..helpers import token_required
from ..models import db, Car, cars_schema

api = Blueprint('api', __name__, url_prefix='/api')

@api.route('/getdata')
def getdata():
    return {''}

@api.route('/cars', methods = ['POST'])
@token_required
def create_car(current_user_token):
    car = request.json['car']
    name = request.json['name']
    model = request.json['model']
    year = request.json['year']
    color = request.json['color']
    gas = request.json['gas']
    mpg = request.json['mpg']
    engine = request.json['engine']
    user_token = current_user_token.token

    print(f'TEST: {current_user_token.token}')

    car = Car(car, name, model, year, color, gas, mpg, engine, user_token=user_token)

    db.session.add(car)
    db.session.commit()

    response = car.schema.dump(car)
    return jsonify(response)


@api.route('/cars', methods = ['GET']) 
@token_required
def get_car(current_user_token):
    a_user = current_user_token.token
    cars = Car.query.filter_by(user_token = a_user).all()
    response = cars_schema.dump(cars)
    return jsonify(response)


@api.route('cars/<id>', methods = ['POST', 'PUT'])
@token_required
def update_car(current_user_token, id):
    car =  Car.query.get(id)
    car.car = request.jsonn['car']
    car.name = request.json['name']
    car.model = request.json['model']
    car.year = request.json['year']
    car.color = request.json['color']
    car.gas = request.json['gas']
    car.mpg = request.json['mpg']
    car.engine = request.json['engine']
    car.user_token = current_user_token.token

    db.session.commit()
    response = cars_schema.dump(car)
    return jsonify(response)


@api.route('cars/<id>', methods = ['DELETE'])
@token_required
def delete_car(current_user_token, id):
    car =  Car.query.get(id)
    db.session.delete(car)
    db.session.commit()
    response = cars_schema.dump(car)
    return jsonify(response)

app/site/routes.py
from flask import Blueprint, render_template

site = Blueprint('site', __name__, template_folder='site_templates')

@site.route('/')
def home():
    return render_template('index.html')

@site.route('/profile')
def profile():
    return render_template('profile.html')

@site.route('/cars')
def cars():
    return render_template('cars.html')

app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta name="Description" content="Enter your description here"/>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.0.1/css/bootstrap.min.css">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">
<link rel="stylesheet" href="../static/main.css">
<title>Ajayi Dealership</title>
</head>
<body>
    <nav class="navbar navbar-expand-lg bg-dark navbar-dark py-3 fixed-top">
        <div class="container">
            <a href="{{ url_for('site.home') }}" class="navbar-brand">Car Inventory</a>
            <button 
                class="navbar-toggler" 
                type="button" 
                data-bs-toggle="collapse" 
                data-bs-target="#navmenu"
            ><span class="navbar-toggler-icon"></span></button>
            <div class="collapse navbar-collapse" id="navmenu">
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a href="{{ url_for('site.home') }}" class="nav-link">Home</a>
                    </li>
                    <li class="nav-item">
                        <a href="{{ url_for('site.cars') }}"   class="nav-link">Cars</a>
                    </li>
                    <li class="nav-item">
                        <a href="{{ url_for('site.profile') }}" class="nav-link">Profile</a>
                    </li>
                    {% if current_user.is_authenticated %}
                    <li class="nav-item">
                        <a href="{{ url_for('auth.logout') }}" class="nav-link">Sign out</a>
                    </li>
                    {% else %}
                    <li class="nav-item">
                        <a href="{{ url_for('auth.signin') }}" class="nav-link">Sign In</a>
                    </li>
                    <li class="nav-item">
                        <a href="{{ url_for('auth.signup')}}" class="nav-link">Sign Up</a>
                    </li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </nav>
    
{% block content %}
{% endblock %}

<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/2.9.2/umd/popper.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.0.1/js/bootstrap.min.js"></script>
</body>
</html>

app/templates/forms.html
<form method="POST">
    {{ form.hidden_tag() }}
    <div class="form-group">
        <fieldset id="email-field">
            {{ form.email.label }}
            {{ form.email(class = 'form-control', placeholder = "Enter Email ") }}
        </fieldset>
    </div>

        <fieldset id="pass-field">
            {{ form.password.label }}
            {{ form.password(class = "form-control", placeholder = " Enter Password ") }}
        </fieldset>

        {{ form.submit_button(class = "btn btn-primary btn-block mt-2")}}

</form>

app/templates/forms1.html
<form method="POST">
    {{ form.hidden_tag() }}
    <div class="form-group">
        <fieldset id="email-field1">
            {{ form.email.label }}
            {{ form.email(class = 'form-control', placeholder = "Enter Email ") }}
        </fieldset>
    </div>

        <fieldset id="pass-field2">
            {{ form.password.label }}
            {{ form.password(class = "form-control", placeholder = " Enter Password ") }}
        </fieldset>

        <fieldset id="pass-field1">
            {{ form.password.label }}
            {{ form.password(class = "form-control", placeholder = " Confirm Password ") }}
        </fieldset>

        <label for="Country" class="area">Country</label>
        <select id="country" name="country">
            <option value="australia">Australia</option>
            <option value="canada">Canada</option>
            <option value="united states">United States</option>
            <option value="russia">Russia</option>
            <option value="south africa">South Africa</option>
            <option value="england">England</option>
        </select>

        {{ form.submit_button(class = "btn btn-primary btn-block mt-2")}}

</form>